// Every cache tag the services use. A read declares some of these in
// `next.tags`; a mutation calls `updateTag` for the ones on screen for the user
// who acted and `revalidateTag(tag, "max")` for the rest. Keeping them here is
// what lets a mutation find the tags its reads declared.
export const TAGS = {
  salons: "salons",
  salon: (id: string) => `salon-${id}`,
  mySalons: "my-salons",
  appointments: "appointments",
  myAppointments: "my-appointments",
  dashboardStats: "dashboard-stats",
  services: "services",
  myServices: "my-services",
  slots: "slots",
  staff: (salonId: string) => `staff-${salonId}`,
  users: "users",
  myCustomers: "my-customers",
  salonApplications: "salon-applications",
  applicationsStatus: "applications-status",
  earnings: "earnings",
  adminTopups: "admin-topups",
  me: "me",
  assistantStatus: "assistant-status",
  authProviders: "auth-providers",
  reviews: "reviews",
  hairstyles: "hairstyles",
  // Back office (`/admin/*`).
  adminMe: "admin-me",
  adminInbox: "admin-inbox",
  adminUsers: "admin-users",
  adminUser: (id: string) => `admin-user-${id}`,
  adminSalons: "admin-salons",
  adminSalon: (id: string) => `admin-salon-${id}`,
  adminBookings: "admin-bookings",
  adminBooking: (id: string) => `admin-booking-${id}`,
  adminAppeals: "admin-appeals",
  adminPayouts: "admin-payouts",
  adminWallets: "admin-wallets",
  adminLedger: "admin-ledger",
  adminReviews: "admin-reviews",
  adminTickets: "admin-tickets",
  adminTicket: (id: string) => `admin-ticket-${id}`,
  adminSettings: "admin-settings",
  publicSettings: "public-settings",
  adminAudit: "admin-audit",
  adminTeam: "admin-team",
  adminAgents: "admin-agents",
  /** Places that have a salon, for the agent area picker. */
  adminAreas: "admin-areas",
  adminAnalytics: "admin-analytics",
  adminSystem: "admin-system",
} as const;
